---
after_failure:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh
before_install:
- "chmod +x scripts/add-key.sh"
- "chmod +x scripts/remove-key.sh"
- "chmod +x scripts/update-bundle.sh"
- "chmod +x scripts/sign-and-upload.sh"
before_script:
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
email: ~
env: ~
global:
- "DEVELOPER_NAME=\"iPhone Distribution: V2Solutions, Inc.\""
- PROFILE_NAME="Distribution"
- APP_PROFILE_PATH="./scripts/profile/"
- APP_SCRIPT_PATH="./scripts/certs/"
- APP_APPLE_CERTIFICATE="apple.cer"
- APP_TEAM_AGENT_DISTRIBUTION_CERTIFICATE="Certificates.cer"
- APP_TEAM_DISTRIBUTION_PRIVATE_KEYS="Key.p12"
- APP_NAME="LendingTree"
- APP_WORKSPACE_PATH="./V2TravisSwifRND.xcworkspace"
- "APP_SCHEME=\"Money Center\""
- INFOPLIST_FILE="./V2TravisSwifRND/Info.plist"
- OUTPUT_FILE_NAME='jsonresponse.text'
- DEV_HOCKEY_APP_ID="8b8b2bcd857148ddaa5d6428c5212874"
- DEV_HOCKEY_APP_TOKEN="9a172758bdfe4fe4b10299bfc9ea519a"
language: objective-c
notifications: ~
on_failure: always
on_success: always
recipients:
- nitesh.meshram@v2solutions.com
script:
- APP_BUILD_ENV=DEV
- "xctool -workspace \"$APP_WORKSPACE_PATH\" -scheme \"$APP_SCHEME.$APP_BUILD_ENV\" -sdk iphoneos -configuration \"$APP_BUILD_ENV\" OBJROOT=\"$PWD/build\" SYMROOT=\"$PWD/build\" ONLY_ACTIVE_ARCH=NO"
- "xctool test -workspace \"$APP_WORKSPACE_PATH\" -scheme \"$APP_SCHEME.$APP_BUILD_ENV\" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO"
